Update build.yaml

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -89,24 +89,26 @@ jobs:
         id: load-json
         run: |
           CONTAINER_DIR=$(basename "${{ matrix.dir }}")
-          SECRET_NAME=$(echo "$CONTAINER_DIR" | tr '[:lower:]' '[:upper:]')_APP_ENV_JSON
-          echo "Using secret name: $SECRET_NAME"
-          if [[ -z "${{ secrets[SECRET_NAME] }}" ]]; then
-            echo "Secret $SECRET_NAME not found!"
-            exit 1
-          fi
-          echo "${{ secrets[SECRET_NAME] }}" > app_env.json
+          echo $CONTAINER_DIR
+          exit 1
+          # SECRET_NAME=$(echo "$CONTAINER_DIR" | tr '[:lower:]' '[:upper:]')_APP_ENV_JSON
+          # echo "Using secret name: $SECRET_NAME"
+          # if [[ -z "${{ secrets[SECRET_NAME] }}" ]]; then
+          #   echo "Secret $SECRET_NAME not found!"
+          #   exit 1
+          # fi
+          # echo "${{ secrets[SECRET_NAME] }}" > app_env.json
 
-      - name: Parse JSON into TF variables
-        id: parse-args
-        run: |
-          VAR_ARGS=""
-          for key in $(jq -r 'keys[]' app_env.json); do
-            val=$(jq -r --arg k "$key" '.[$k]' app_env.json)
-            tfkey=$(echo "$key" | tr '[:upper:]' '[:lower:]')
-            VAR_ARGS="$VAR_ARGS -var=\"${tfkey}=${val}\""
-          done
-          echo "TF_VARS=${VAR_ARGS}" >> $GITHUB_ENV
+      # - name: Parse JSON into TF variables
+      #   id: parse-args
+      #   run: |
+      #     VAR_ARGS=""
+      #     for key in $(jq -r 'keys[]' app_env.json); do
+      #       val=$(jq -r --arg k "$key" '.[$k]' app_env.json)
+      #       tfkey=$(echo "$key" | tr '[:upper:]' '[:lower:]')
+      #       VAR_ARGS="$VAR_ARGS -var=\"${tfkey}=${val}\""
+      #     done
+      #     echo "TF_VARS=${VAR_ARGS}" >> $GITHUB_ENV
 
 
       - name: 📦 Terraform Init
